### ISSUE TITLE
Remove automatic ENV var usage except inside config files

### ISSUE THREAD

**Issue by nyurik** [maplibre/martin#1052]
Per discussion in #1050, we should scale down on Martin's implicit usage of the environment variables. This is too unpredictable and could result in all sorts of weird behavior. Instead, Martin should only rely on two things:  command line parameters and config files.  The config files will continue supporting explicit environment variables, e.g. `connection_string: ${MY_DATABASE_URL}` or even with a fallback like `connection_string: ${MY_DATABASE_URL:-postgresql://postgres@localhost/db}`

### Tasks

* [ ] Ensure ALL [env vars](https://maplibre.org/martin/env-vars.html) can be set at least with the config file, or best -- with both config file and CLI parameters. (I think they already are, but double check)
* [ ] Detect if any of [these env vars](https://maplibre.org/martin/env-vars.html) are set, and if they are, show a warning with clear instructions on doing it with either CLI parameters or with config (or both, or a link to docs).
  * For example, if `DATABASE_URL` is set, suggest to use `martin "$DATABASE_URL"` instead, or add `postgres.connection_string: ${DATABASE_URL}` to the config file.
* [ ] Remove any magical handling of the env vars from the code (except for the above detection and warnings)
* [ ] Update documentation

### Alternatives
Instead of removing, we could follow other Rust tools pattern, and rename all environment variables to be `MARTIN_*`, e.g. `MARTIN_DATABASE_URL`. In my opinion, we should still disable the existing ones as they create too many conflicts with other tooling that relies on the same env vars.

**Comment by reddynitish** [comment]
Hi! I’d like to work on this issue. I’ll first inventory the current implicit environment-variable reads and confirm each setting has an explicit CLI/config equivalent, then remove the implicit behavior behind clear migration warnings and update the documentation/tests. I’ll keep the change scoped to the env-var behavior described here. Could you assign #1052 to me if that approach looks good?

**Comment by CommanderStorm** [comment]
sure, feel free to investigate.
